//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddEdit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public string Article { get; set; }
        public decimal MinCost { get; set; }
        public string Image { get; set; }
        public int TypeProductId { get; set; }
        public int QuantityPerson { get; set; }
        public int NumberPlant { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
